micronaut:
  application:
    name: documents-service
  server:
    host: ${SERVICE_HOST:0.0.0.0}
    port: ${SERVICE_PORT:-1}
---
datasources:
  default:
    url: jdbc:h2:tcp://172.17.0.1:1521/test;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
---
jpa:
    default:
        packages-to-scan:
        - 'pl.altkom.asc.lab.micronaut.poc.documents.domain'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
---
jackson:
    serialization:
        failOnEmptyBeans: false
        writeDatesAsTimestamps: true
---
kafka:
    bootstrap:
        servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"
---
consul:
    client:
        registration:
            enabled: true
            ip-addr: ${CONSUL_REG_IP}
            prefer-ip-address: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
tracing:
    zipkin:
        enabled: true
        http:
            url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
            sampler:
                probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
---
jsreport:
  host: ${JSREPORT_HOST:localhost}
  port: ${JSREPORT_PORT:5488}
