micronaut:
  application:
    name: auth-service
  server:
    host: ${SERVICE_HOST:0.0.0.0}
    port: ${SERVICE_PORT:8090}
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 86400
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
---
datasources:
  default:
    url: jdbc:h2:tcp://172.17.0.1:1521/test;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.