micronaut:
  application:
    name: gateway
  server:
    host: ${SERVICE_HOST:0.0.0.0}
    port: ${SERVICE_PORT:8081}
    cors:
      enabled: true
  http:
    services:
      product-service:
        urls:
          - http://172.17.0.1:10001
        path: /api/v1/web/guest/poc/serverless-product-service/products
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
---
consul:
  client:
    registration:
      enabled: false
      ip-addr: ${CONSUL_REG_IP}
      prefer-ip-address: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
---
jackson:
  dateFormat: dd.MM.yyyy