version: '2'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: poc_jsreport
    hostname: jsreport
    networks:
      - poc 
    ports:
      - 5488:5488
  consul:
    image: consul
    container_name: poc_consul
    # network_mode: host
    networks:
      - poc 
    ports:
      - 8500:8500
  zipkin:
    image: openzipkin/zipkin
    container_name: poc_zipkin
    # network_mode: host
    networks:
      - poc 
    ports:
      - 9411:9411
  mongo:
    image: mongo
    container_name: poc_mongo
    # network_mode: host
    volumes:
      - ~/.tmp/vol2/mongo_data:/data/db
    networks:
      - poc 
    ports:
      - 27017:27017
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: poc_kafka
    hostname: kafkaserver
    # network_mode: host
    networks:
      - poc 
    ports:
      - 2182:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: poc_kafkamanager
    # network_mode: host
    networks:
      - poc 
    ports:
      - 8999:9000
    environment:
      ZK_HOSTS: "172.17.0.1:2182"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: poc_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - poc 
    ports:
      - 9200:9200
  mn-documents-service:
    build: ./documents-service
    image: mn-documents-service
    container_name: poc_mn-documents-service
    environment: 
      SERVICE_PORT: 8083
      SERVICE_HOST: 0.0.0.0
      KAFKA_HOST: 172.17.0.1
      CONSUL_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      JSREPORT_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    # network_mode: host
    ports:
      - 8083:8083
    networks:
      - poc 
  mn-policy-service:
    build: ./policy-service
    image: mn-policy-service
    container_name: poc_mn-policy-service
    environment: 
      SERVICE_PORT: 8086
      SERVICE_HOST: 0.0.0.0
      KAFKA_HOST: 172.17.0.1
      CONSUL_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    ports:
      - 8086:8086
    # network_mode: host
    networks:
      - poc 
  mn-policy-search-service:
    build: ./policy-search-service
    image: mn-policy-search-service
    container_name: poc_mn-policy-search-service
    environment: 
      SERVICE_PORT: 8085
      SERVICE_HOST: 0.0.0.0
      KAFKA_HOST: 172.17.0.1
      CONSUL_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      ELASTIC_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    ports:
      - 8085:8085
    # network_mode: host
    networks:
      - poc 
  mn-pricing-service:
    build: ./pricing-service
    image: mn-pricing-service
    container_name: poc_mn-pricing-service
    environment: 
      SERVICE_PORT: 8087
      SERVICE_HOST: 0.0.0.0
      CONSUL_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    ports: 
      - 8087:8087
    # network_mode: host
    networks:
      - poc 
  mn-payment-service:
    build: ./payment-service
    image: mn-payment-service
    container_name: poc_mn-payment-service
    environment: 
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8084
      CONSUL_HOST: 172.17.0.1
      KAFKA_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    ports:
      - 8084:8084
    # network_mode: host
    networks:
      - poc 
  mn-product-service:
    build: ./product-service
    image: mn-product-service
    container_name: poc_mn-product-service
    environment: 
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8088
      CONSUL_HOST: 172.17.0.1
      KAFKA_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      MG_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    ports:
      - 8088:8088
    # network_mode: host
    networks:
      - poc 
  mn-auth-service:
    build: ./auth-service
    image: mn-auth-service
    container_name: poc_mn-auth-service
    environment: 
      ZIPKIN_HOST: 172.17.0.1
      CONSUL_HOST: 172.17.0.1
    # network_mode: host
    ports:
      - 8090:8090
    networks:
      - poc 
  mn-chat-service:
    build: ./chat-service
    image: mn-chat-service
    container_name: poc_mn-chat-service
    environment: 
      CONSUL_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
    # network_mode: host
    ports:
      - 8787:8787
    networks:
      - poc 
  mn-dashboard-service:
    build: ./dashboard-service
    image: mn-dashboard-service
    container_name: poc_mn-dashboard-service
    # network_mode: host
    environment: 
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8082
      CONSUL_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
      KAFKA_HOST: 172.17.0.1
      ELASTIC_HOST: 172.17.0.1
    ports:
      - 8082:8082
    networks:
      - poc 
  mn-agent-portal-gateway:
    build: ./agent-portal-gateway
    image: mn-agent-portal-gateway
    container_name: poc_mn-agent-portal-gateway
    environment: 
      CONSUL_HOST: 172.17.0.1
      ZIPKIN_HOST: 172.17.0.1
      CONSUL_REG_IP: 172.17.0.1
      SERVICE_HOST: 0.0.0.0
    # network_mode: host
    networks:
      - poc 
    ports:
      - 8081:8081
  mn-web-vue:
    build: ./web-vue
    image: mn-web-vue
    container_name: poc_mn-web-vue
    environment: 
      VUE_APP_BACKEND_URL: "http://172.17.0.1:8081/api/"
      VUE_APP_AUTH_URL: "http://172.17.0.1:8090/"
      VUE_APP_CHAT_URL: "ws://172.17.0.1:8787/"
      GATEWAY_URL: "http://172.17.0.1:8081"
      AUTH_URL: "http://172.17.0.1:8090"
    # network_mode: host
    networks:
      - poc 
    ports:
      - 8080:8080

networks:
  poc: