micronaut:
  application:
    name: payment-service
  server:
    host: ${SERVICE_HOST:0.0.0.0}
    port: ${SERVICE_PORT:-1}
---
kafka:
  bootstrap:
    servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}"
---
consul:
  client:
    registration:
      enabled: true
      ip-addr: ${CONSUL_REG_IP}
      prefer-ip-address: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
hystrix:
  stream:
    enabled: true
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.
---
payments:
    importDir: c:\bank_imports
---
datasources:
  default:
    url: jdbc:h2:tcp://172.17.0.1:1521/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
---
jpa:
 default:
    packages-to-scan:
        - 'pl.altkom.asc.lab.micronaut.poc.payment.domain'
    properties:
        hibernate:
            hbm2ddl:
                auto: update
            show_sql: true
