micronaut:
  application:
    name: serverless-product-service
  server:
    host: ${SERVICE_HOST:0.0.0.0}
    port: ${SERVICE_PORT:7088}
#  metrics:
#    enabled: true
---
jackson:
  bean-introspection-module: true
---
#endpoints:
#  health:
#    enabled: true
#    sensitive: false
#  metrics:
#    enabled: true
#    sensitive: false
---
mongodb:
    uri: "mongodb://${MG_HOST:172.17.0.1}:${MG_PORT:27019}/demo"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
---
consul:
  client:
    registration:
      enabled: true
      ip-addr: ${CONSUL_REG_IP:172.17.0.1}
      prefer-ip-address: true
    defaultZone: "${CONSUL_HOST:172.17.0.1}:${CONSUL_PORT:8500}"
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:172.17.0.1}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.

