micronaut:
  application:
    name: policy-service
  server:
    host: 0.0.0.0
    # host: 172.17.0.1
    port: 9088
---
datasources:
  default:
    url: jdbc:h2:tcp://172.17.0.1:1521/test;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
---
http:
    services:
      pricing-service:
        urls:
          - http://172.17.0.1:10001
        path: /api/v1/web/guest/poc/serverless-pricing-service/pricing
---
jpa:
 default:
    packages-to-scan:
        - 'pl.altkom.asc.lab.micronaut.poc.serverless.policy.domain'
    properties:
        hibernate:
            hbm2ddl:
                auto: update
            show_sql: true
---
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true
# ---
# consul:
#   client:
#     registration:
#       enabled: false
#     defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
